-- ─────────────────────────────────────────────────────────────────────────────
-- RISK-12: index enrollments.retake_of.
--
-- Superseded-row detection (`retakeOf: { in: [...] }` in the dashboard
-- definitions, the status tracker and the reminder sweep) filters on this
-- column, which had no index, so each lookup scanned the table.
--
-- Plain CREATE INDEX rather than CONCURRENTLY: `prisma migrate deploy` runs a
-- migration inside a transaction, and CREATE INDEX CONCURRENTLY cannot run in
-- one. It briefly blocks writes to enrollments while it builds, which at this
-- table's size is sub-second. IF NOT EXISTS makes a re-run a no-op.
--
-- Index only: adding the foreign key / Prisma relation is out of scope here.
--
-- HAND-AUTHORED from `prisma migrate diff`. No
-- `DROP INDEX "manual_chunks_embedding_hnsw_idx";` — the pgvector HNSW index is
-- raw-SQL-managed and autogenerated migrations re-emit a DROP for it.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE INDEX IF NOT EXISTS "enrollments_retake_of_idx" ON "enrollments"("retake_of");
