-- Rename tables to snake_case plural and columns to snake_case.
-- Constraints and indexes are renamed to match Prisma's naming convention
-- on the new names, keeping future `prisma migrate` runs drift-free.

-- RenameColumn
ALTER TABLE "AuditorPack" RENAME COLUMN "generatedBy" TO "generated_by";
ALTER TABLE "AuditorPack" RENAME COLUMN "downloadUrl" TO "download_url";
ALTER TABLE "AuditorPack" RENAME COLUMN "generatedAt" TO "generated_at";
ALTER TABLE "User" RENAME COLUMN "passwordResetRequired" TO "password_reset_required";
ALTER TABLE "User" RENAME COLUMN "organizationId" TO "organization_id";
ALTER TABLE "User" RENAME COLUMN "authProvider" TO "auth_provider";
ALTER TABLE "User" RENAME COLUMN "emailVerified" TO "email_verified";
ALTER TABLE "User" RENAME COLUMN "mfaEnabled" TO "mfa_enabled";
ALTER TABLE "User" RENAME COLUMN "mfaVerifiedAt" TO "mfa_verified_at";
ALTER TABLE "User" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "User" RENAME COLUMN "updatedAt" TO "updated_at";
ALTER TABLE "Profile" RENAME COLUMN "firstName" TO "first_name";
ALTER TABLE "Profile" RENAME COLUMN "lastName" TO "last_name";
ALTER TABLE "Profile" RENAME COLUMN "fullName" TO "full_name";
ALTER TABLE "Profile" RENAME COLUMN "jobTitle" TO "job_title";
ALTER TABLE "Profile" RENAME COLUMN "companyName" TO "company_name";
ALTER TABLE "Profile" RENAME COLUMN "avatarUrl" TO "avatar_url";
ALTER TABLE "Profile" RENAME COLUMN "hasSeenAuditorWelcome" TO "has_seen_auditor_welcome";
ALTER TABLE "Profile" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "Profile" RENAME COLUMN "updatedAt" TO "updated_at";
ALTER TABLE "Invite" RENAME COLUMN "organizationId" TO "organization_id";
ALTER TABLE "Invite" RENAME COLUMN "expiresAt" TO "expires_at";
ALTER TABLE "Invite" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "Invite" RENAME COLUMN "invitedBy" TO "invited_by";
ALTER TABLE "VerificationToken" RENAME COLUMN "firstName" TO "first_name";
ALTER TABLE "VerificationToken" RENAME COLUMN "lastName" TO "last_name";
ALTER TABLE "MfaFactor" RENAME COLUMN "userId" TO "user_id";
ALTER TABLE "MfaFactor" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "MfaFactor" RENAME COLUMN "updatedAt" TO "updated_at";
ALTER TABLE "MfaRecoveryCode" RENAME COLUMN "userId" TO "user_id";
ALTER TABLE "MfaRecoveryCode" RENAME COLUMN "codeHash" TO "code_hash";
ALTER TABLE "MfaRecoveryCode" RENAME COLUMN "usedAt" TO "used_at";
ALTER TABLE "MfaRecoveryCode" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "CourseCategory" RENAME COLUMN "isSystem" TO "is_system";
ALTER TABLE "CourseCategory" RENAME COLUMN "organizationId" TO "organization_id";
ALTER TABLE "CourseCategory" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "StandardManual" RENAME COLUMN "storagePath" TO "storage_path";
ALTER TABLE "StandardManual" RENAME COLUMN "uploadedBy" TO "uploaded_by";
ALTER TABLE "StandardManual" RENAME COLUMN "isActive" TO "is_active";
ALTER TABLE "StandardManual" RENAME COLUMN "processedAt" TO "processed_at";
ALTER TABLE "StandardManual" RENAME COLUMN "chunkCount" TO "chunk_count";
ALTER TABLE "StandardManual" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "ManualChunk" RENAME COLUMN "manualId" TO "manual_id";
ALTER TABLE "ManualChunk" RENAME COLUMN "chunkIndex" TO "chunk_index";
ALTER TABLE "ManualChunk" RENAME COLUMN "pageNumber" TO "page_number";
ALTER TABLE "ManualChunk" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "ManualChunkCategory" RENAME COLUMN "chunkId" TO "chunk_id";
ALTER TABLE "ManualChunkCategory" RENAME COLUMN "categoryId" TO "category_id";
ALTER TABLE "Course" RENAME COLUMN "categoryId" TO "category_id";
ALTER TABLE "Course" RENAME COLUMN "createdBy" TO "created_by";
ALTER TABLE "Course" RENAME COLUMN "skillLevel" TO "skill_level";
ALTER TABLE "Course" RENAME COLUMN "previewVideoStorageUri" TO "preview_video_storage_uri";
ALTER TABLE "Course" RENAME COLUMN "previewVideoDurationSeconds" TO "preview_video_duration_seconds";
ALTER TABLE "Course" RENAME COLUMN "previewMediaStatus" TO "preview_media_status";
ALTER TABLE "Course" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "Course" RENAME COLUMN "updatedAt" TO "updated_at";
ALTER TABLE "Course" RENAME COLUMN "promptVersion" TO "prompt_version";
ALTER TABLE "Course" RENAME COLUMN "rawCourseJson" TO "raw_course_json";
ALTER TABLE "Course" RENAME COLUMN "rawQuizJson" TO "raw_quiz_json";
ALTER TABLE "Course" RENAME COLUMN "rawArticleMarkdown" TO "raw_article_markdown";
ALTER TABLE "Course" RENAME COLUMN "rawArticleMeta" TO "raw_article_meta";
ALTER TABLE "Course" RENAME COLUMN "rawJudgeJson" TO "raw_judge_json";
ALTER TABLE "Course" RENAME COLUMN "rawSlidesJson" TO "raw_slides_json";
ALTER TABLE "Course" RENAME COLUMN "approvedByUserId" TO "approved_by_user_id";
ALTER TABLE "Course" RENAME COLUMN "approvedAt" TO "approved_at";
ALTER TABLE "Course" RENAME COLUMN "isGlobal" TO "is_global";
ALTER TABLE "CourseModule" RENAME COLUMN "courseId" TO "course_id";
ALTER TABLE "CourseModule" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "CourseModule" RENAME COLUMN "updatedAt" TO "updated_at";
ALTER TABLE "Lesson" RENAME COLUMN "courseId" TO "course_id";
ALTER TABLE "Lesson" RENAME COLUMN "slideContent" TO "slide_content";
ALTER TABLE "Lesson" RENAME COLUMN "videoProvider" TO "video_provider";
ALTER TABLE "Lesson" RENAME COLUMN "videoStorageUri" TO "video_storage_uri";
ALTER TABLE "Lesson" RENAME COLUMN "videoDurationSeconds" TO "video_duration_seconds";
ALTER TABLE "Lesson" RENAME COLUMN "mediaStatus" TO "media_status";
ALTER TABLE "Lesson" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "Lesson" RENAME COLUMN "updatedAt" TO "updated_at";
ALTER TABLE "Lesson" RENAME COLUMN "moduleId" TO "module_id";
ALTER TABLE "CourseArtifact" RENAME COLUMN "courseId" TO "course_id";
ALTER TABLE "CourseArtifact" RENAME COLUMN "storageUri" TO "storage_uri";
ALTER TABLE "CourseArtifact" RENAME COLUMN "mimeType" TO "mime_type";
ALTER TABLE "CourseArtifact" RENAME COLUMN "sizeBytes" TO "size_bytes";
ALTER TABLE "CourseArtifact" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "CourseVersion" RENAME COLUMN "courseId" TO "course_id";
ALTER TABLE "CourseVersion" RENAME COLUMN "documentVersionId" TO "document_version_id";
ALTER TABLE "CourseVersion" RENAME COLUMN "publishedAt" TO "published_at";
ALTER TABLE "CourseAssignment" RENAME COLUMN "organizationId" TO "organization_id";
ALTER TABLE "CourseAssignment" RENAME COLUMN "courseId" TO "course_id";
ALTER TABLE "CourseAssignment" RENAME COLUMN "assignedByAdminId" TO "assigned_by_admin_id";
ALTER TABLE "CourseAssignment" RENAME COLUMN "scheduleAt" TO "schedule_at";
ALTER TABLE "CourseAssignment" RENAME COLUMN "renewalCycle" TO "renewal_cycle";
ALTER TABLE "CourseAssignment" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "CourseAssignment" RENAME COLUMN "updatedAt" TO "updated_at";
ALTER TABLE "AssignmentReminder" RENAME COLUMN "assignmentId" TO "assignment_id";
ALTER TABLE "AssignmentReminder" RENAME COLUMN "offsetMinutes" TO "offset_minutes";
ALTER TABLE "Document" RENAME COLUMN "userId" TO "user_id";
ALTER TABLE "Document" RENAME COLUMN "originalName" TO "original_name";
ALTER TABLE "Document" RENAME COLUMN "mimeType" TO "mime_type";
ALTER TABLE "Document" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "Document" RENAME COLUMN "updatedAt" TO "updated_at";
ALTER TABLE "DocumentVersion" RENAME COLUMN "documentId" TO "document_id";
ALTER TABLE "DocumentVersion" RENAME COLUMN "storagePath" TO "storage_path";
ALTER TABLE "DocumentVersion" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "PhiReport" RENAME COLUMN "documentVersionId" TO "document_version_id";
ALTER TABLE "PhiReport" RENAME COLUMN "hasPHI" TO "has_phi";
ALTER TABLE "PhiReport" RENAME COLUMN "detectedEntities" TO "detected_entities";
ALTER TABLE "PhiReport" RENAME COLUMN "scannedAt" TO "scanned_at";
ALTER TABLE "MappingEvidence" RENAME COLUMN "documentVersionId" TO "document_version_id";
ALTER TABLE "MappingEvidence" RENAME COLUMN "standardId" TO "standard_id";
ALTER TABLE "MappingEvidence" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "MappingEvidence" RENAME COLUMN "updatedAt" TO "updated_at";
ALTER TABLE "Enrollment" RENAME COLUMN "userId" TO "user_id";
ALTER TABLE "Enrollment" RENAME COLUMN "courseId" TO "course_id";
ALTER TABLE "Enrollment" RENAME COLUMN "videoPositionSeconds" TO "video_position_seconds";
ALTER TABLE "Enrollment" RENAME COLUMN "startedAt" TO "started_at";
ALTER TABLE "Enrollment" RENAME COLUMN "completedAt" TO "completed_at";
ALTER TABLE "Enrollment" RENAME COLUMN "attestedAt" TO "attested_at";
ALTER TABLE "Enrollment" RENAME COLUMN "attestationSignature" TO "attestation_signature";
ALTER TABLE "Enrollment" RENAME COLUMN "attestationRole" TO "attestation_role";
ALTER TABLE "Enrollment" RENAME COLUMN "assignedByAdminId" TO "assigned_by_admin_id";
ALTER TABLE "Enrollment" RENAME COLUMN "lockedAt" TO "locked_at";
ALTER TABLE "Enrollment" RENAME COLUMN "retakeOf" TO "retake_of";
ALTER TABLE "Enrollment" RENAME COLUMN "retakeReason" TO "retake_reason";
ALTER TABLE "Enrollment" RENAME COLUMN "assignmentId" TO "assignment_id";
ALTER TABLE "Enrollment" RENAME COLUMN "accessAt" TO "access_at";
ALTER TABLE "Certificate" RENAME COLUMN "enrollmentId" TO "enrollment_id";
ALTER TABLE "Certificate" RENAME COLUMN "userId" TO "user_id";
ALTER TABLE "Certificate" RENAME COLUMN "courseId" TO "course_id";
ALTER TABLE "Certificate" RENAME COLUMN "issuedAt" TO "issued_at";
ALTER TABLE "Certificate" RENAME COLUMN "pdfStoragePath" TO "pdf_storage_path";
ALTER TABLE "Certificate" RENAME COLUMN "pdfGeneratedAt" TO "pdf_generated_at";
ALTER TABLE "Job" RENAME COLUMN "userId" TO "user_id";
ALTER TABLE "Job" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "Job" RENAME COLUMN "updatedAt" TO "updated_at";
ALTER TABLE "Notification" RENAME COLUMN "userId" TO "user_id";
ALTER TABLE "Notification" RENAME COLUMN "isRead" TO "is_read";
ALTER TABLE "Notification" RENAME COLUMN "linkUrl" TO "link_url";
ALTER TABLE "Notification" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "Notification" RENAME COLUMN "resolvedAt" TO "resolved_at";
ALTER TABLE "OrgCourseOffering" RENAME COLUMN "organizationId" TO "organization_id";
ALTER TABLE "OrgCourseOffering" RENAME COLUMN "courseId" TO "course_id";
ALTER TABLE "OrgCourseOffering" RENAME COLUMN "addedByAdminId" TO "added_by_admin_id";
ALTER TABLE "OrgCourseOffering" RENAME COLUMN "customTitle" TO "custom_title";
ALTER TABLE "OrgCourseOffering" RENAME COLUMN "customDescription" TO "custom_description";
ALTER TABLE "OrgCourseOffering" RENAME COLUMN "customIntro" TO "custom_intro";
ALTER TABLE "OrgCourseOffering" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "Organization" RENAME COLUMN "staffCount" TO "staff_count";
ALTER TABLE "Organization" RENAME COLUMN "primaryContact" TO "primary_contact";
ALTER TABLE "Organization" RENAME COLUMN "primaryEmail" TO "primary_email";
ALTER TABLE "Organization" RENAME COLUMN "zipCode" TO "zip_code";
ALTER TABLE "Organization" RENAME COLUMN "licenseNumber" TO "license_number";
ALTER TABLE "Organization" RENAME COLUMN "isHipaaCompliant" TO "is_hipaa_compliant";
ALTER TABLE "Organization" RENAME COLUMN "hasAuditorAccess" TO "has_auditor_access";
ALTER TABLE "Organization" RENAME COLUMN "primaryBusinessType" TO "primary_business_type";
ALTER TABLE "Organization" RENAME COLUMN "additionalBusinessTypes" TO "additional_business_types";
ALTER TABLE "Organization" RENAME COLUMN "programServices" TO "program_services";
ALTER TABLE "Organization" RENAME COLUMN "joinCode" TO "join_code";
ALTER TABLE "Organization" RENAME COLUMN "joinCodeExpiresAt" TO "join_code_expires_at";
ALTER TABLE "Organization" RENAME COLUMN "stripeCustomerId" TO "stripe_customer_id";
ALTER TABLE "Organization" RENAME COLUMN "inactivityTimeoutMinutes" TO "inactivity_timeout_minutes";
ALTER TABLE "Organization" RENAME COLUMN "requireMfa" TO "require_mfa";
ALTER TABLE "Organization" RENAME COLUMN "complianceDocumentUrl" TO "compliance_document_url";
ALTER TABLE "Organization" RENAME COLUMN "complianceDocumentName" TO "compliance_document_name";
ALTER TABLE "Organization" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "Organization" RENAME COLUMN "updatedAt" TO "updated_at";
ALTER TABLE "Subscription" RENAME COLUMN "organizationId" TO "organization_id";
ALTER TABLE "Subscription" RENAME COLUMN "stripeSubscriptionId" TO "stripe_subscription_id";
ALTER TABLE "Subscription" RENAME COLUMN "stripePriceId" TO "stripe_price_id";
ALTER TABLE "Subscription" RENAME COLUMN "billingCycle" TO "billing_cycle";
ALTER TABLE "Subscription" RENAME COLUMN "currentPeriodStart" TO "current_period_start";
ALTER TABLE "Subscription" RENAME COLUMN "currentPeriodEnd" TO "current_period_end";
ALTER TABLE "Subscription" RENAME COLUMN "cancelAtPeriodEnd" TO "cancel_at_period_end";
ALTER TABLE "Subscription" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "Subscription" RENAME COLUMN "updatedAt" TO "updated_at";
ALTER TABLE "Invoice" RENAME COLUMN "organizationId" TO "organization_id";
ALTER TABLE "Invoice" RENAME COLUMN "stripeInvoiceId" TO "stripe_invoice_id";
ALTER TABLE "Invoice" RENAME COLUMN "invoiceNumber" TO "invoice_number";
ALTER TABLE "Invoice" RENAME COLUMN "amountPaid" TO "amount_paid";
ALTER TABLE "Invoice" RENAME COLUMN "invoiceUrl" TO "invoice_url";
ALTER TABLE "Invoice" RENAME COLUMN "pdfUrl" TO "pdf_url";
ALTER TABLE "Invoice" RENAME COLUMN "periodStart" TO "period_start";
ALTER TABLE "Invoice" RENAME COLUMN "periodEnd" TO "period_end";
ALTER TABLE "Invoice" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "Quiz" RENAME COLUMN "lessonId" TO "lesson_id";
ALTER TABLE "Quiz" RENAME COLUMN "courseId" TO "course_id";
ALTER TABLE "Quiz" RENAME COLUMN "passingScore" TO "passing_score";
ALTER TABLE "Quiz" RENAME COLUMN "allowedAttempts" TO "allowed_attempts";
ALTER TABLE "Quiz" RENAME COLUMN "timeLimit" TO "time_limit";
ALTER TABLE "Quiz" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "Question" RENAME COLUMN "quizId" TO "quiz_id";
ALTER TABLE "Question" RENAME COLUMN "correctAnswer" TO "correct_answer";
ALTER TABLE "QuizAttempt" RENAME COLUMN "enrollmentId" TO "enrollment_id";
ALTER TABLE "QuizAttempt" RENAME COLUMN "quizId" TO "quiz_id";
ALTER TABLE "QuizAttempt" RENAME COLUMN "timeTaken" TO "time_taken";
ALTER TABLE "QuizAttempt" RENAME COLUMN "attemptCount" TO "attempt_count";
ALTER TABLE "QuizAttempt" RENAME COLUMN "completedAt" TO "completed_at";

-- RenameConstraint (primary keys)
ALTER TABLE "AuditorPack" RENAME CONSTRAINT "AuditorPack_pkey" TO "auditor_packs_pkey";
ALTER TABLE "User" RENAME CONSTRAINT "User_pkey" TO "users_pkey";
ALTER TABLE "Profile" RENAME CONSTRAINT "Profile_pkey" TO "profiles_pkey";
ALTER TABLE "Invite" RENAME CONSTRAINT "Invite_pkey" TO "invites_pkey";
ALTER TABLE "MfaFactor" RENAME CONSTRAINT "MfaFactor_pkey" TO "mfa_factors_pkey";
ALTER TABLE "MfaRecoveryCode" RENAME CONSTRAINT "MfaRecoveryCode_pkey" TO "mfa_recovery_codes_pkey";
ALTER TABLE "CourseCategory" RENAME CONSTRAINT "CourseCategory_pkey" TO "course_categories_pkey";
ALTER TABLE "StandardManual" RENAME CONSTRAINT "StandardManual_pkey" TO "standard_manuals_pkey";
ALTER TABLE "ManualChunk" RENAME CONSTRAINT "ManualChunk_pkey" TO "manual_chunks_pkey";
ALTER TABLE "ManualChunkCategory" RENAME CONSTRAINT "ManualChunkCategory_pkey" TO "manual_chunk_categories_pkey";
ALTER TABLE "Course" RENAME CONSTRAINT "Course_pkey" TO "courses_pkey";
ALTER TABLE "CourseModule" RENAME CONSTRAINT "CourseModule_pkey" TO "course_modules_pkey";
ALTER TABLE "Lesson" RENAME CONSTRAINT "Lesson_pkey" TO "lessons_pkey";
ALTER TABLE "CourseArtifact" RENAME CONSTRAINT "CourseArtifact_pkey" TO "course_artifacts_pkey";
ALTER TABLE "CourseVersion" RENAME CONSTRAINT "CourseVersion_pkey" TO "course_versions_pkey";
ALTER TABLE "CourseAssignment" RENAME CONSTRAINT "CourseAssignment_pkey" TO "course_assignments_pkey";
ALTER TABLE "AssignmentReminder" RENAME CONSTRAINT "AssignmentReminder_pkey" TO "assignment_reminders_pkey";
ALTER TABLE "Document" RENAME CONSTRAINT "Document_pkey" TO "documents_pkey";
ALTER TABLE "DocumentVersion" RENAME CONSTRAINT "DocumentVersion_pkey" TO "document_versions_pkey";
ALTER TABLE "PhiReport" RENAME CONSTRAINT "PhiReport_pkey" TO "phi_reports_pkey";
ALTER TABLE "MappingEvidence" RENAME CONSTRAINT "MappingEvidence_pkey" TO "mapping_evidence_pkey";
ALTER TABLE "Enrollment" RENAME CONSTRAINT "Enrollment_pkey" TO "enrollments_pkey";
ALTER TABLE "Certificate" RENAME CONSTRAINT "Certificate_pkey" TO "certificates_pkey";
ALTER TABLE "Job" RENAME CONSTRAINT "Job_pkey" TO "jobs_pkey";
ALTER TABLE "Notification" RENAME CONSTRAINT "Notification_pkey" TO "notifications_pkey";
ALTER TABLE "OrgCourseOffering" RENAME CONSTRAINT "OrgCourseOffering_pkey" TO "org_course_offerings_pkey";
ALTER TABLE "Organization" RENAME CONSTRAINT "Organization_pkey" TO "organizations_pkey";
ALTER TABLE "Subscription" RENAME CONSTRAINT "Subscription_pkey" TO "subscriptions_pkey";
ALTER TABLE "Invoice" RENAME CONSTRAINT "Invoice_pkey" TO "invoices_pkey";
ALTER TABLE "Quiz" RENAME CONSTRAINT "Quiz_pkey" TO "quizzes_pkey";
ALTER TABLE "Question" RENAME CONSTRAINT "Question_pkey" TO "questions_pkey";
ALTER TABLE "QuizAttempt" RENAME CONSTRAINT "QuizAttempt_pkey" TO "quiz_attempts_pkey";

-- RenameConstraint (foreign keys)
ALTER TABLE "User" RENAME CONSTRAINT "User_organizationId_fkey" TO "users_organization_id_fkey";
ALTER TABLE "Profile" RENAME CONSTRAINT "Profile_id_fkey" TO "profiles_id_fkey";
ALTER TABLE "Invite" RENAME CONSTRAINT "Invite_organizationId_fkey" TO "invites_organization_id_fkey";
ALTER TABLE "MfaFactor" RENAME CONSTRAINT "MfaFactor_userId_fkey" TO "mfa_factors_user_id_fkey";
ALTER TABLE "MfaRecoveryCode" RENAME CONSTRAINT "MfaRecoveryCode_userId_fkey" TO "mfa_recovery_codes_user_id_fkey";
ALTER TABLE "CourseCategory" RENAME CONSTRAINT "CourseCategory_organizationId_fkey" TO "course_categories_organization_id_fkey";
ALTER TABLE "ManualChunk" RENAME CONSTRAINT "ManualChunk_manualId_fkey" TO "manual_chunks_manual_id_fkey";
ALTER TABLE "ManualChunkCategory" RENAME CONSTRAINT "ManualChunkCategory_chunkId_fkey" TO "manual_chunk_categories_chunk_id_fkey";
ALTER TABLE "ManualChunkCategory" RENAME CONSTRAINT "ManualChunkCategory_categoryId_fkey" TO "manual_chunk_categories_category_id_fkey";
ALTER TABLE "Course" RENAME CONSTRAINT "Course_categoryId_fkey" TO "courses_category_id_fkey";
ALTER TABLE "Course" RENAME CONSTRAINT "Course_approvedByUserId_fkey" TO "courses_approved_by_user_id_fkey";
ALTER TABLE "Course" RENAME CONSTRAINT "Course_createdBy_fkey" TO "courses_created_by_fkey";
ALTER TABLE "CourseModule" RENAME CONSTRAINT "CourseModule_courseId_fkey" TO "course_modules_course_id_fkey";
ALTER TABLE "Lesson" RENAME CONSTRAINT "Lesson_courseId_fkey" TO "lessons_course_id_fkey";
ALTER TABLE "Lesson" RENAME CONSTRAINT "Lesson_moduleId_fkey" TO "lessons_module_id_fkey";
ALTER TABLE "CourseArtifact" RENAME CONSTRAINT "CourseArtifact_courseId_fkey" TO "course_artifacts_course_id_fkey";
ALTER TABLE "CourseVersion" RENAME CONSTRAINT "CourseVersion_courseId_fkey" TO "course_versions_course_id_fkey";
ALTER TABLE "CourseVersion" RENAME CONSTRAINT "CourseVersion_documentVersionId_fkey" TO "course_versions_document_version_id_fkey";
ALTER TABLE "CourseAssignment" RENAME CONSTRAINT "CourseAssignment_organizationId_fkey" TO "course_assignments_organization_id_fkey";
ALTER TABLE "CourseAssignment" RENAME CONSTRAINT "CourseAssignment_courseId_fkey" TO "course_assignments_course_id_fkey";
ALTER TABLE "AssignmentReminder" RENAME CONSTRAINT "AssignmentReminder_assignmentId_fkey" TO "assignment_reminders_assignment_id_fkey";
ALTER TABLE "Document" RENAME CONSTRAINT "Document_userId_fkey" TO "documents_user_id_fkey";
ALTER TABLE "DocumentVersion" RENAME CONSTRAINT "DocumentVersion_documentId_fkey" TO "document_versions_document_id_fkey";
ALTER TABLE "PhiReport" RENAME CONSTRAINT "PhiReport_documentVersionId_fkey" TO "phi_reports_document_version_id_fkey";
ALTER TABLE "MappingEvidence" RENAME CONSTRAINT "MappingEvidence_documentVersionId_fkey" TO "mapping_evidence_document_version_id_fkey";
ALTER TABLE "Enrollment" RENAME CONSTRAINT "Enrollment_assignmentId_fkey" TO "enrollments_assignment_id_fkey";
ALTER TABLE "Enrollment" RENAME CONSTRAINT "Enrollment_courseId_fkey" TO "enrollments_course_id_fkey";
ALTER TABLE "Enrollment" RENAME CONSTRAINT "Enrollment_userId_fkey" TO "enrollments_user_id_fkey";
ALTER TABLE "Certificate" RENAME CONSTRAINT "Certificate_userId_fkey" TO "certificates_user_id_fkey";
ALTER TABLE "Certificate" RENAME CONSTRAINT "Certificate_enrollmentId_fkey" TO "certificates_enrollment_id_fkey";
ALTER TABLE "Certificate" RENAME CONSTRAINT "Certificate_courseId_fkey" TO "certificates_course_id_fkey";
ALTER TABLE "Notification" RENAME CONSTRAINT "Notification_userId_fkey" TO "notifications_user_id_fkey";
ALTER TABLE "OrgCourseOffering" RENAME CONSTRAINT "OrgCourseOffering_organizationId_fkey" TO "org_course_offerings_organization_id_fkey";
ALTER TABLE "OrgCourseOffering" RENAME CONSTRAINT "OrgCourseOffering_courseId_fkey" TO "org_course_offerings_course_id_fkey";
ALTER TABLE "Subscription" RENAME CONSTRAINT "Subscription_organizationId_fkey" TO "subscriptions_organization_id_fkey";
ALTER TABLE "Invoice" RENAME CONSTRAINT "Invoice_organizationId_fkey" TO "invoices_organization_id_fkey";
ALTER TABLE "Quiz" RENAME CONSTRAINT "Quiz_lessonId_fkey" TO "quizzes_lesson_id_fkey";
ALTER TABLE "Quiz" RENAME CONSTRAINT "Quiz_courseId_fkey" TO "quizzes_course_id_fkey";
ALTER TABLE "Question" RENAME CONSTRAINT "Question_quizId_fkey" TO "questions_quiz_id_fkey";
ALTER TABLE "QuizAttempt" RENAME CONSTRAINT "QuizAttempt_enrollmentId_fkey" TO "quiz_attempts_enrollment_id_fkey";
ALTER TABLE "QuizAttempt" RENAME CONSTRAINT "QuizAttempt_quizId_fkey" TO "quiz_attempts_quiz_id_fkey";

-- RenameIndex (unique & non-unique)
ALTER INDEX "User_email_key" RENAME TO "users_email_key";
ALTER INDEX "User_organizationId_idx" RENAME TO "users_organization_id_idx";
ALTER INDEX "Profile_email_key" RENAME TO "profiles_email_key";
ALTER INDEX "Invite_token_key" RENAME TO "invites_token_key";
ALTER INDEX "Invite_email_idx" RENAME TO "invites_email_idx";
ALTER INDEX "Invite_token_idx" RENAME TO "invites_token_idx";
ALTER INDEX "VerificationToken_identifier_token_key" RENAME TO "verification_tokens_identifier_token_key";
ALTER INDEX "MfaFactor_userId_idx" RENAME TO "mfa_factors_user_id_idx";
ALTER INDEX "MfaRecoveryCode_userId_idx" RENAME TO "mfa_recovery_codes_user_id_idx";
ALTER INDEX "CourseCategory_slug_key" RENAME TO "course_categories_slug_key";
ALTER INDEX "CourseCategory_organizationId_idx" RENAME TO "course_categories_organization_id_idx";
ALTER INDEX "CourseCategory_isSystem_idx" RENAME TO "course_categories_is_system_idx";
ALTER INDEX "StandardManual_isActive_idx" RENAME TO "standard_manuals_is_active_idx";
ALTER INDEX "ManualChunk_manualId_idx" RENAME TO "manual_chunks_manual_id_idx";
ALTER INDEX "ManualChunk_manualId_chunkIndex_idx" RENAME TO "manual_chunks_manual_id_chunk_index_idx";
ALTER INDEX "Course_createdBy_idx" RENAME TO "courses_created_by_idx";
ALTER INDEX "Course_status_idx" RENAME TO "courses_status_idx";
ALTER INDEX "Course_categoryId_idx" RENAME TO "courses_category_id_idx";
ALTER INDEX "Course_type_idx" RENAME TO "courses_type_idx";
ALTER INDEX "Course_isGlobal_idx" RENAME TO "courses_is_global_idx";
ALTER INDEX "CourseModule_courseId_idx" RENAME TO "course_modules_course_id_idx";
ALTER INDEX "Lesson_moduleId_idx" RENAME TO "lessons_module_id_idx";
ALTER INDEX "CourseArtifact_courseId_idx" RENAME TO "course_artifacts_course_id_idx";
ALTER INDEX "CourseArtifact_courseId_type_version_key" RENAME TO "course_artifacts_course_id_type_version_key";
ALTER INDEX "CourseAssignment_organizationId_idx" RENAME TO "course_assignments_organization_id_idx";
ALTER INDEX "CourseAssignment_courseId_idx" RENAME TO "course_assignments_course_id_idx";
ALTER INDEX "AssignmentReminder_assignmentId_idx" RENAME TO "assignment_reminders_assignment_id_idx";
ALTER INDEX "Document_userId_idx" RENAME TO "documents_user_id_idx";
ALTER INDEX "PhiReport_documentVersionId_key" RENAME TO "phi_reports_document_version_id_key";
ALTER INDEX "Enrollment_userId_courseId_idx" RENAME TO "enrollments_user_id_course_id_idx";
ALTER INDEX "Enrollment_courseId_idx" RENAME TO "enrollments_course_id_idx";
ALTER INDEX "Enrollment_completedAt_idx" RENAME TO "enrollments_completed_at_idx";
ALTER INDEX "Enrollment_assignmentId_idx" RENAME TO "enrollments_assignment_id_idx";
ALTER INDEX "Certificate_enrollmentId_key" RENAME TO "certificates_enrollment_id_key";
ALTER INDEX "Certificate_userId_idx" RENAME TO "certificates_user_id_idx";
ALTER INDEX "Certificate_courseId_idx" RENAME TO "certificates_course_id_idx";
ALTER INDEX "Job_userId_idx" RENAME TO "jobs_user_id_idx";
ALTER INDEX "Job_status_idx" RENAME TO "jobs_status_idx";
ALTER INDEX "Notification_userId_idx" RENAME TO "notifications_user_id_idx";
ALTER INDEX "OrgCourseOffering_organizationId_idx" RENAME TO "org_course_offerings_organization_id_idx";
ALTER INDEX "OrgCourseOffering_courseId_idx" RENAME TO "org_course_offerings_course_id_idx";
ALTER INDEX "OrgCourseOffering_organizationId_courseId_key" RENAME TO "org_course_offerings_organization_id_course_id_key";
ALTER INDEX "Organization_slug_key" RENAME TO "organizations_slug_key";
ALTER INDEX "Organization_joinCode_key" RENAME TO "organizations_join_code_key";
ALTER INDEX "Organization_stripeCustomerId_key" RENAME TO "organizations_stripe_customer_id_key";
ALTER INDEX "Subscription_organizationId_key" RENAME TO "subscriptions_organization_id_key";
ALTER INDEX "Subscription_stripeSubscriptionId_key" RENAME TO "subscriptions_stripe_subscription_id_key";
ALTER INDEX "Invoice_stripeInvoiceId_key" RENAME TO "invoices_stripe_invoice_id_key";
ALTER INDEX "Invoice_organizationId_idx" RENAME TO "invoices_organization_id_idx";
ALTER INDEX "Quiz_lessonId_key" RENAME TO "quizzes_lesson_id_key";
ALTER INDEX "Quiz_courseId_key" RENAME TO "quizzes_course_id_key";
ALTER INDEX "QuizAttempt_enrollmentId_quizId_key" RENAME TO "quiz_attempts_enrollment_id_quiz_id_key";

-- RenameTable
ALTER TABLE "AuditorPack" RENAME TO "auditor_packs";
ALTER TABLE "User" RENAME TO "users";
ALTER TABLE "Profile" RENAME TO "profiles";
ALTER TABLE "Invite" RENAME TO "invites";
ALTER TABLE "VerificationToken" RENAME TO "verification_tokens";
ALTER TABLE "MfaFactor" RENAME TO "mfa_factors";
ALTER TABLE "MfaRecoveryCode" RENAME TO "mfa_recovery_codes";
ALTER TABLE "CourseCategory" RENAME TO "course_categories";
ALTER TABLE "StandardManual" RENAME TO "standard_manuals";
ALTER TABLE "ManualChunk" RENAME TO "manual_chunks";
ALTER TABLE "ManualChunkCategory" RENAME TO "manual_chunk_categories";
ALTER TABLE "Course" RENAME TO "courses";
ALTER TABLE "CourseModule" RENAME TO "course_modules";
ALTER TABLE "Lesson" RENAME TO "lessons";
ALTER TABLE "CourseArtifact" RENAME TO "course_artifacts";
ALTER TABLE "CourseVersion" RENAME TO "course_versions";
ALTER TABLE "CourseAssignment" RENAME TO "course_assignments";
ALTER TABLE "AssignmentReminder" RENAME TO "assignment_reminders";
ALTER TABLE "Document" RENAME TO "documents";
ALTER TABLE "DocumentVersion" RENAME TO "document_versions";
ALTER TABLE "PhiReport" RENAME TO "phi_reports";
ALTER TABLE "MappingEvidence" RENAME TO "mapping_evidence";
ALTER TABLE "Enrollment" RENAME TO "enrollments";
ALTER TABLE "Certificate" RENAME TO "certificates";
ALTER TABLE "Job" RENAME TO "jobs";
ALTER TABLE "Notification" RENAME TO "notifications";
ALTER TABLE "OrgCourseOffering" RENAME TO "org_course_offerings";
ALTER TABLE "Organization" RENAME TO "organizations";
ALTER TABLE "Subscription" RENAME TO "subscriptions";
ALTER TABLE "Invoice" RENAME TO "invoices";
ALTER TABLE "Quiz" RENAME TO "quizzes";
ALTER TABLE "Question" RENAME TO "questions";
ALTER TABLE "QuizAttempt" RENAME TO "quiz_attempts";

