export type CourseWithStats = {
  id: string;
  title: string;
  description: string | null;
  thumbnail: string | null;
  status: string;
  type: string; // 'video' | 'text'
  duration: number | null;
  createdAt: Date;
  updatedAt: Date;
  lessonsCount: number;
  enrollmentsCount: number;
  completionRate: number;
  /**
   * Document the course was generated from, when the caller loaded that lineage.
   * Null for forked courses (duplicates and adopted prebuilts carry no
   * `CourseVersion` of their own), and absent from views that do not query it.
   */
  sourceDocumentId?: string | null;
  /**
   * True for rows sourced from the platform-wide published video catalog that
   * this organization has not adopted. Such a course is authored by another
   * tenant, so it is view-only here: rename/delete would mutate it for every
   * organization and the assign action rejects it on its creator-org check.
   */
  isGlobalCatalog?: boolean;
};

/**
 * Training document attached to a wizard module. Kept JSON-serializable (no
 * `File`) so the sessionStorage draft round-trips it.
 */
export interface CourseWizardModuleDocument {
  documentId: string;
  fileName: string;
  fileSize: number;
  mimeType: string;
}

export interface CourseWizardModule {
  title: string;
  objective: string;
  completionDeadlineDays: number | null;
  documentId: string | null;
  fileName?: string;
  fileSize?: number;
  mimeType?: string;
}

export interface CourseWizardReminder {
  value: number;
  unit: 'days';
}

export interface CourseWizardData {
  categoryId: string;
  title: string;
  description: string;
  difficulty: string;
  duration: string;
  notesCount: string;
  /**
   * Days a learner gets to complete the whole course, set on the Course Details
   * step. Distinct from the AI-estimated `duration` (how long the material takes
   * to work through) and from a module's own `completionDeadlineDays`.
   */
  completionDeadlineDays: number | null;
  objectives: string[];
  quizTitle: string;
  quizQuestionCount: string;
  quizDifficulty: string;
  quizQuestionType: string;
  quizDuration: string;
  quizPassMark: string;
  quizAttempts: string;
  assignments: string[];
  dueDate: string;
  dueTime: string;
  modules: CourseWizardModule[];
  // Set on the audience step; pre-fills the assignment step, which lands in a
  // later phase of the design alignment.
  audience: 'general' | 'specific';
  audienceRoles: string[];
  // Carried by the 9-step wizard shell but not yet read by any step: the
  // assignment screen lands in a later phase of the design alignment. Kept here
  // so drafts saved now survive that phase.
  assignMode: 'roles' | 'email';
  assignRoles: string[];
  dueDeadlineEnabled: boolean;
  reminders: CourseWizardReminder[];
  recurringEnabled: boolean;
  renewalCycle: string;
}

export interface CourseDocument {
  id: string;
  name: string;
  type: 'pdf' | 'docx';
  status: 'analyzed' | 'pending';
  selected: boolean;
  file?: File;
}

export interface GeneratedLesson {
  title: string;
  content: string;
  duration: string;
}

export interface RenderableModule extends GeneratedLesson {
  id: string;
  slideContent: string;
  order: number;
  sectionId?: string;
  keyPoints?: string[];
  /**
   * Wizard module this lesson was generated from. A course generated before
   * per-module generation has a single, untagged set of lessons.
   */
  moduleIndex?: number;
  moduleTitle?: string;
}

import { Prisma } from '@/generated/prisma/client';
import { QuizQuestion } from './quiz';

/**
 * One wizard module's share of a generated course: the lessons and questions
 * produced from its own source document, plus the module metadata the wizard
 * collected. Persisted as a `CourseModule` row.
 */
export interface GeneratedCourseModule {
  moduleIndex: number;
  title: string;
  objective: string | null;
  completionDeadlineDays: number | null;
  documentId: string | null;
  lessons: RenderableModule[];
  quiz: QuizQuestion[];
  warning?: string;
}

export interface GeneratedCourse {
  title: string;
  description: string;
  difficulty: string;
  duration: string;
  objectives: string[];
  /** Every module's lessons, flattened in module order. */
  modules: RenderableModule[];
  quiz: QuizQuestion[];
  /**
   * Per-module breakdown of the same content. Absent for courses generated by
   * the single-document pipeline.
   */
  courseModules?: GeneratedCourseModule[];
  // Raw data fields for v4.6
  rawArticleMeta?: unknown;
  rawArticleMarkdown?: string;
  rawSlidesJson?: unknown;
  rawJudgeJson?: unknown;
  rawQuizJson?: unknown;
  rawCourseJson?: unknown;
  sourceText?: string;
  warning?: string;
}

/**
 * Field selection for the course-detail read path (getCourseById /
 * getCourseForOrgView). Explicit `select` (not `include`) so the query fetches
 * only what the course-detail and preview UIs actually consume — never the heavy
 * raw-AI JSON columns on Course, the full user rows behind enrollments (password
 * hash / MFA secrets), or the per-question answer columns. Every field kept here
 * is read by `TrainingDetails` and/or `CoursePreview`; narrowing it will drop a
 * UI section, so audit those components before removing a field.
 */
export const courseDetailSelect = {
  id: true,
  title: true,
  description: true,
  type: true,
  duration: true,
  status: true,
  /** Splits `draft` into "Needs Review" (F-051 gate) vs a plain unpublished draft. */
  reviewRequired: true,
  updatedAt: true,
  overview: true,
  objectives: true,
  skillLevel: true,
  previewVideoStorageUri: true,
  createdByOrgUserId: true,
  modules: {
    orderBy: { order: 'asc' as const },
    select: {
      id: true,
      title: true,
      order: true,
      lessons: {
        orderBy: { order: 'asc' as const },
        select: { id: true, title: true, order: true, videoDurationSeconds: true },
      },
    },
  },
  quiz: {
    select: {
      title: true,
      passingScore: true,
      questions: { select: { id: true } },
    },
  },
  lessons: {
    orderBy: { order: 'asc' as const },
    select: {
      id: true,
      title: true,
      order: true,
      videoStorageUri: true,
      videoDurationSeconds: true,
      quiz: { select: { passingScore: true } },
    },
  },
  enrollments: {
    select: {
      id: true,
      organizationUserId: true,
      status: true,
      score: true,
      progress: true,
      // Role lives on the membership, and identity on the global User row, so
      // the roster reaches through OrganizationUser rather than a `user` FK.
      organizationUser: {
        select: {
          userId: true,
          role: true,
          user: { select: { email: true, fullName: true } },
        },
      },
      certificate: { select: { id: true, issuedAt: true } },
    },
  },
  creator: {
    select: {
      userId: true,
      organizationId: true,
      user: { select: { email: true, fullName: true } },
    },
  },
} satisfies Prisma.CourseSelect;

export type CourseWithRelations = Prisma.CourseGetPayload<{ select: typeof courseDetailSelect }>;

export type EnrollmentWithRelations = Prisma.EnrollmentGetPayload<{
  include: {
    quizAttempts: true;
    organizationUser: {
      include: { user: true; organization: true };
    };
    course: true;
    certificate: true;
  };
}>;

// Use where an enrollment must carry its assignment batch (schedule / renewal /
// reminders). Kept separate from EnrollmentWithRelations so existing enrollment
// queries aren't forced to include the assignment relation.
export type EnrollmentWithAssignment = Prisma.EnrollmentGetPayload<{
  include: {
    assignment: { include: { reminderStages: true } };
  };
}>;
