'use client';

import React, { useMemo, useState } from 'react';
import { CirclePlus, Sparkles } from 'lucide-react';
import { generateSingleQuestion, regenerateQuiz } from '@/app/actions/quiz-ai';
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from '@/components/ui/accordion';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from '@/components/ui/alert-dialog';
import { Alert } from '@/components/ui/alert';
import { Button } from '@/components/ui/button';
import { QuizQuestion } from '@/types/quiz';
import { CourseWizardData } from '@/types/course';
import { wizardSubtitleClass, wizardTitleClass } from './wizardFormClasses';
import { logger } from '@/lib/logger';

interface Step6QuizReviewProps {
  data: CourseWizardData;
  quiz?: QuizQuestion[];
  courseId?: string;
  rawContext?: string;
  onQuizUpdate: (quiz: QuizQuestion[]) => void;
}

/**
 * A module's share of the quiz. `questionIndexes` point back into the flat
 * `quiz` array so editing and insertion keep working on the single list the
 * wizard persists. `tag` is the module identity copied onto questions added
 * here, so a manual question groups with the module it was written for.
 */
interface QuizSection {
  key: string;
  title: string;
  moduleIndex?: number;
  tag?: Pick<QuizQuestion, 'moduleIndex' | 'moduleTitle'>;
  questionIndexes: number[];
}

const UNTAGGED_SECTION_KEY = 'untagged';

// Client-side fallback only. Both actions already return a user-safe message
// for every outcome they can name, including the wall-clock timeout — this
// covers the transport itself failing.
const UNEXPECTED_ERROR_MESSAGE =
  'Something went wrong talking to the server. Please check your connection and try again.';

/** The single accordion group the frames draw around the whole question list. */
const QUIZ_GROUP_KEY = 'quiz';

const formInputClass =
  'w-full rounded-md border-[1.5px] border-border px-4 py-3 text-base text-foreground outline-none transition-colors placeholder:text-muted-foreground focus:border-primary';
const formLabelClass = 'mb-2 block text-sm font-semibold text-text-secondary';

const emptyQuestion = (): QuizQuestion => ({
  question: '',
  options: ['', '', '', ''],
  answer: 0,
  type: 'multiple_choice',
});

/**
 * Groups the flat quiz by the module each question was generated from (Phase 6
 * tags every question with `moduleIndex`/`moduleTitle`). Courses generated by
 * the single-document pipeline carry no tags, so they collapse into one section
 * named after the course.
 */
function groupQuestionsByModule(questions: QuizQuestion[], courseTitle: string): QuizSection[] {
  const byKey = new Map<string, QuizSection>();

  questions.forEach((question, index) => {
    const key =
      question.moduleIndex !== undefined
        ? `module-${question.moduleIndex}`
        : question.moduleTitle?.trim() || UNTAGGED_SECTION_KEY;

    const existing = byKey.get(key);
    if (existing) {
      existing.questionIndexes.push(index);
      return;
    }

    const isTagged = question.moduleIndex !== undefined || Boolean(question.moduleTitle?.trim());
    byKey.set(key, {
      key,
      title: question.moduleTitle?.trim() || '',
      moduleIndex: question.moduleIndex,
      tag: isTagged
        ? { moduleIndex: question.moduleIndex, moduleTitle: question.moduleTitle }
        : undefined,
      questionIndexes: [index],
    });
  });

  const sections = [...byKey.values()];
  if (sections.length === 0) {
    sections.push({ key: UNTAGGED_SECTION_KEY, title: '', questionIndexes: [] });
  }

  const onlyUntaggedSection = sections.length === 1 && !sections[0].tag;
  return sections.map((section, position) => ({
    ...section,
    title:
      section.title ||
      (onlyUntaggedSection ? courseTitle.trim() || 'Section 1' : `Section ${position + 1}`),
  }));
}

export default function Step6QuizReview({
  data,
  quiz,
  courseId,
  rawContext,
  onQuizUpdate,
}: Step6QuizReviewProps) {
  const questions = useMemo(() => quiz || [], [quiz]);
  const [addingSectionKey, setAddingSectionKey] = useState<string | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [isRegenerating, setIsRegenerating] = useState(false);
  const [confirmRegenerateOpen, setConfirmRegenerateOpen] = useState(false);
  const [editingIndex, setEditingIndex] = useState<number | null>(null);
  const [editingQuestion, setEditingQuestion] = useState<QuizQuestion | null>(null);
  const [newQuestion, setNewQuestion] = useState<QuizQuestion>(emptyQuestion);
  const [actionError, setActionError] = useState<string | null>(null);

  const sections = useMemo(
    () => groupQuestionsByModule(questions, data.title || ''),
    [questions, data.title],
  );

  // The list is drawn flat, so a manually added question appends to the end —
  // which is the last module's share, and therefore the tag it inherits.
  const addTargetSection = sections[sections.length - 1];
  const quizGroupTitle = data.quizTitle?.trim() || data.title?.trim() || 'Quiz Title';

  const startAdding = (sectionKey: string) => {
    setAddingSectionKey(sectionKey);
    setNewQuestion(emptyQuestion());
  };

  const handleAddQuestion = (section: QuizSection) => {
    if (!newQuestion.question.trim() || newQuestion.options.some((o) => !o.trim())) {
      setActionError('Please fill in all fields.');
      return;
    }
    // Insert right after the section's last question so the flat quiz the wizard
    // persists stays grouped in module order.
    const insertAt = section.questionIndexes.length
      ? section.questionIndexes[section.questionIndexes.length - 1] + 1
      : questions.length;
    const updatedQuiz = [...questions];
    updatedQuiz.splice(insertAt, 0, { ...newQuestion, ...section.tag });

    onQuizUpdate(updatedQuiz);
    setAddingSectionKey(null);
    setNewQuestion(emptyQuestion());
  };

  const updateOption = (index: number, value: string) => {
    const newOptions = [...newQuestion.options];
    newOptions[index] = value;
    setNewQuestion({ ...newQuestion, options: newOptions });
  };

  /**
   * Prompt context for both AI paths. A course is generated from one document
   * (D1), so it is described by its own title and objectives — there is no
   * per-module title left to name in the prompt.
   */
  const buildAiContext = () => {
    const baseContext =
      rawContext?.trim() || `${data.title || ''}\n${data.description || ''}`.trim();
    const objectives = data.objectives?.filter(Boolean) ?? [];

    return [
      data.title ? `Course: ${data.title}` : '',
      objectives.length > 0 ? `Objectives: ${objectives.join('; ')}` : '',
      baseContext,
    ]
      .filter(Boolean)
      .join('\n\n');
  };

  const handleGenerateQuestion = async () => {
    const targetCourseId = courseId;
    const context = buildAiContext();

    if (!targetCourseId && !context) {
      setActionError(
        'Cannot generate a question right now. The course may not be fully saved yet.',
      );
      return;
    }

    try {
      setActionError(null);
      setIsGenerating(true);
      const res = await generateSingleQuestion({ courseId: targetCourseId, context });
      if (res.success && res.question) {
        setNewQuestion({
          question: res.question.question,
          options: res.question.options,
          answer: res.question.answer,
          type: res.question.type,
          explanation: res.question.explanation,
        });
      } else {
        setActionError(res.error || 'Failed to generate question with AI.');
      }
    } catch (error) {
      logger.error({ msg: 'Failed to call AI generation:', err: error });
      setActionError(UNEXPECTED_ERROR_MESSAGE);
    } finally {
      setIsGenerating(false);
    }
  };

  // Requested vs. generated: the wizard blocks publishing until at least one
  // question exists (CourseWizard.isNextDisabled). Explain that block inline, and
  // surface a partial fill (fewer than requested) as a non-blocking warning that
  // mirrors the server-side assessCourseQuality copy.
  const requestedCount = parseInt(data.quizQuestionCount ?? '', 10) || 0;
  const showEmptyBanner = questions.length === 0;
  const showPartialBanner =
    questions.length > 0 && requestedCount > 0 && questions.length < requestedCount;

  const handleRegenerateQuiz = async () => {
    setConfirmRegenerateOpen(false);

    const targetCourseId = courseId;
    const context = buildAiContext();

    if (!targetCourseId && !context) {
      setActionError(
        'Cannot regenerate the quiz right now. The course may not be fully saved yet.',
      );
      return;
    }

    try {
      setActionError(null);
      setIsRegenerating(true);
      const res = await regenerateQuiz({
        courseId: targetCourseId,
        context,
        questionCount: requestedCount || questions.length,
      });

      if (res.success && res.questions) {
        onQuizUpdate(
          res.questions.map((question) => ({
            question: question.question,
            options: question.options,
            answer: question.answer,
            type: question.type,
            explanation: question.explanation,
          })),
        );
        setEditingIndex(null);
        setEditingQuestion(null);
        setAddingSectionKey(null);
      } else {
        setActionError(res.error || 'Failed to regenerate the quiz.');
      }
    } catch (error) {
      logger.error({ msg: '[course] Quiz regeneration failed', err: error });
      setActionError(UNEXPECTED_ERROR_MESSAGE);
    } finally {
      setIsRegenerating(false);
    }
  };

  const renderAddForm = (section: QuizSection) => (
    <div className="w-full rounded-md border border-border p-5">
      <h3 className="mb-5 text-lg font-bold text-foreground">Add New Question</h3>

      <div className="mb-5">
        <label className={formLabelClass} htmlFor={`newQuestionText-${section.key}`}>
          Question Text
        </label>
        <input
          id={`newQuestionText-${section.key}`}
          type="text"
          className={formInputClass}
          placeholder="Enter your question here..."
          value={newQuestion.question}
          onChange={(e) => setNewQuestion({ ...newQuestion, question: e.target.value })}
        />
      </div>

      <div className="mb-5">
        <label className={formLabelClass}>Options (Select correct answer)</label>
        <div className="flex flex-col gap-3">
          {newQuestion.options.map((opt, i) => (
            <div key={i} className="flex items-center gap-3">
              <input
                type="radio"
                name={`correctAnswer-${section.key}`}
                aria-label={`Mark option ${i + 1} correct`}
                checked={newQuestion.answer === i}
                onChange={() => setNewQuestion({ ...newQuestion, answer: i })}
              />
              <input
                type="text"
                className={formInputClass}
                value={opt}
                onChange={(e) => updateOption(i, e.target.value)}
                placeholder={`Option ${i + 1}`}
                disabled={newQuestion.type === 'true_false'}
              />
            </div>
          ))}
        </div>
      </div>

      <div className="mt-6 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <Button
          variant="outline"
          onClick={(e) => {
            e.preventDefault();
            handleGenerateQuestion();
          }}
          disabled={isGenerating}
        >
          {isGenerating ? (
            'Generating...'
          ) : (
            <>
              <Sparkles className="mr-2 size-3.5" />
              Generate with AI
            </>
          )}
        </Button>
        <div className="flex gap-3">
          <Button variant="ghost" onClick={() => setAddingSectionKey(null)}>
            Cancel
          </Button>
          <Button variant="default" onClick={() => handleAddQuestion(section)}>
            Save Question
          </Button>
        </div>
      </div>
    </div>
  );

  const renderQuestion = (question: QuizQuestion, index: number, position: number) => {
    if (editingIndex === index && editingQuestion) {
      return (
        <div key={index} className="w-full rounded-md border border-border p-5">
          <h4 className="m-0 mb-4 text-base font-semibold">Edit Question {position}</h4>

          <div className="mb-5">
            <label className={formLabelClass} htmlFor={`editQuestionText-${index}`}>
              Question Text
            </label>
            <input
              id={`editQuestionText-${index}`}
              type="text"
              className={formInputClass}
              value={editingQuestion.question}
              onChange={(e) => setEditingQuestion({ ...editingQuestion, question: e.target.value })}
            />
          </div>

          <div className="mb-5">
            <label className={formLabelClass}>Options (Select correct answer)</label>
            <div className="flex flex-col gap-3">
              {editingQuestion.options.map((opt, i) => (
                <div key={i} className="flex items-center gap-3">
                  <input
                    type="radio"
                    name={`editCorrectAnswer-${index}`}
                    aria-label={`Mark option ${i + 1} correct`}
                    checked={editingQuestion.answer === i}
                    onChange={() => setEditingQuestion({ ...editingQuestion, answer: i })}
                  />
                  <input
                    type="text"
                    className={formInputClass}
                    value={opt}
                    onChange={(e) => {
                      const newOptions = [...editingQuestion.options];
                      newOptions[i] = e.target.value;
                      setEditingQuestion({ ...editingQuestion, options: newOptions });
                    }}
                    disabled={editingQuestion.type === 'true_false'}
                  />
                </div>
              ))}
            </div>
          </div>

          <div className="mt-6 flex justify-end gap-3">
            <Button
              variant="ghost"
              size="sm"
              onClick={() => {
                setEditingIndex(null);
                setEditingQuestion(null);
              }}
            >
              Cancel
            </Button>
            <Button
              variant="default"
              size="sm"
              onClick={() => {
                if (
                  !editingQuestion.question.trim() ||
                  editingQuestion.options.some((o) => !o.trim())
                ) {
                  setActionError('Please fill in all fields.');
                  return;
                }
                const updatedQuiz = [...questions];
                updatedQuiz[index] = editingQuestion;
                onQuizUpdate(updatedQuiz);
                setEditingIndex(null);
                setEditingQuestion(null);
              }}
            >
              Save Changes
            </Button>
          </div>
        </div>
      );
    }

    return (
      <div key={index} className="w-full rounded-md bg-background-secondary p-5">
        <div className="mb-4 flex items-start justify-between gap-4">
          <div className="flex-1 text-base font-semibold leading-relaxed text-foreground">
            <span className="mr-2 font-bold">{position}.</span>
            {question.question}
          </div>
          <Button
            variant="outline"
            size="sm"
            className="shrink-0 rounded-sm border-border bg-background"
            onClick={() => {
              setEditingIndex(index);
              setEditingQuestion(question);
            }}
          >
            Edit
          </Button>
        </div>
        <div className="flex flex-col gap-2.5 pl-6">
          {question.options.map((opt, optIndex) => (
            <div
              key={optIndex}
              className="flex items-center rounded-lg border border-transparent px-3 py-2 text-sm text-text-secondary transition-colors hover:bg-background-secondary"
            >
              <div
                className={`mr-3 h-[18px] w-[18px] shrink-0 rounded-full border-2 ${
                  question.answer === optIndex
                    ? 'border-success bg-success shadow-[inset_0_0_0_3px_white]'
                    : 'border-input'
                }`}
              />
              {opt}
              {question.answer === optIndex && (
                <span className="ml-2 text-xs font-semibold text-success">(Correct)</span>
              )}
            </div>
          ))}
        </div>

        {question.explanation && (
          <div className="mt-3 rounded-md border border-border bg-background-secondary px-4 py-3 text-[13px] leading-relaxed">
            <div className="mb-1.5 flex items-start gap-1.5 font-semibold text-success">
              <span>✓</span>
              <span>Correct: {question.explanation.correctExplanation}</span>
            </div>
            {question.explanation.incorrectOptions &&
              Object.entries(question.explanation.incorrectOptions).map(([key, text]) => (
                <div key={key} className="mt-2 flex items-start gap-1.5 text-error">
                  <span>✕</span>
                  <span>
                    Option {String.fromCharCode(65 + parseInt(key))}: {text}
                  </span>
                </div>
              ))}
            {question.evidence?.moduleSectionHeading && (
              <div className="mt-2 text-[11px] text-text-tertiary">
                Source: {question.evidence.moduleSectionHeading}
              </div>
            )}
          </div>
        )}
      </div>
    );
  };

  return (
    <div className="flex w-full flex-col gap-10 md:gap-14">
      <div className="flex flex-col items-center gap-3">
        <h2 className={wizardTitleClass}>Review Quiz Questions</h2>
        <p className={wizardSubtitleClass}>
          Review the quiz questions generated by AI or add your own.
        </p>
      </div>

      <div className="flex w-full flex-col rounded-md border border-border bg-background p-5 md:p-6">
        {showEmptyBanner && (
          <Alert variant="error" title="No quiz questions were generated" className="mb-6 shrink-0">
            AI didn&apos;t generate the requested number of quiz questions. Add questions manually
            below or go back a step to retry generation.
          </Alert>
        )}
        {showPartialBanner && (
          <Alert variant="warning" title="Fewer questions than requested" className="mb-6 shrink-0">
            The quiz has only {questions.length} of the {requestedCount} requested questions. You
            can add more manually below, or go back a step to retry generation.
          </Alert>
        )}
        {actionError && (
          <Alert variant="error" className="mb-6 shrink-0">
            {actionError}
          </Alert>
        )}
        <div className="mb-5 flex shrink-0 flex-col gap-3 sm:flex-row sm:items-center sm:justify-between sm:gap-4">
          <div className="flex flex-col gap-1">
            <div className="text-base font-bold text-foreground md:text-[17px]">
              Editable quiz questions
            </div>
            <div className="text-[13px] text-text-secondary">{questions.length} questions</div>
          </div>

          <AlertDialog open={confirmRegenerateOpen} onOpenChange={setConfirmRegenerateOpen}>
            <AlertDialogTrigger asChild>
              <Button
                variant="default"
                className="h-11 shrink-0 self-start px-6 text-sm font-semibold sm:self-auto"
                loading={isRegenerating}
              >
                Regenerate Quiz
              </Button>
            </AlertDialogTrigger>
            <AlertDialogContent>
              <AlertDialogHeader>
                <AlertDialogTitle>Regenerate the whole quiz?</AlertDialogTitle>
                <AlertDialogDescription>
                  AI will write a fresh set of questions from the course content. Every question
                  below is replaced, so any edits you have made here — and any questions you added
                  yourself — will be lost.
                </AlertDialogDescription>
              </AlertDialogHeader>
              <AlertDialogFooter>
                <AlertDialogCancel>Cancel</AlertDialogCancel>
                <AlertDialogAction onClick={handleRegenerateQuiz}>
                  Regenerate Quiz
                </AlertDialogAction>
              </AlertDialogFooter>
            </AlertDialogContent>
          </AlertDialog>
        </div>

        {/* One collapsible headed by the quiz title, holding one ungrouped,
            continuously numbered list — the module grouping survives in the
            data (see `sections`), it is simply no longer drawn. */}
        <Accordion type="multiple" defaultValue={[QUIZ_GROUP_KEY]} className="flex flex-col">
          <AccordionItem
            value={QUIZ_GROUP_KEY}
            className="rounded-none border-none bg-transparent px-0"
          >
            <AccordionTrigger className="rounded-sm border border-border px-4 py-3.5 text-base font-semibold text-foreground hover:no-underline">
              {quizGroupTitle}
            </AccordionTrigger>
            <AccordionContent className="flex flex-col gap-3 px-0 pt-3 pb-0">
              {questions.length === 0 ? (
                <div className="rounded-md border border-dashed border-border bg-background-secondary p-10 text-center italic text-text-tertiary">
                  No questions available. Add one below.
                </div>
              ) : (
                questions.map((question, index) => renderQuestion(question, index, index + 1))
              )}
            </AccordionContent>
          </AccordionItem>
        </Accordion>

        {addingSectionKey !== null ? (
          <div className="mt-3">{renderAddForm(addTargetSection)}</div>
        ) : (
          <div className="mt-3 flex items-center justify-between gap-4 rounded-sm border border-border px-4 py-3.5">
            <span className="text-base font-semibold text-foreground">Add new question</span>
            <Button
              variant="ghost"
              size="icon-sm"
              aria-label="Add new question"
              className="shrink-0 rounded-full text-primary hover:bg-primary/10"
              onClick={() => startAdding(addTargetSection.key)}
            >
              <CirclePlus className="size-6" aria-hidden="true" />
            </Button>
          </div>
        )}
      </div>
    </div>
  );
}
