'use client';

import React, { useMemo, useState } from 'react';
import { Plus, Sparkles } from 'lucide-react';
import { generateSingleQuestion } from '@/app/actions/quiz-ai';
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from '@/components/ui/accordion';
import { Alert } from '@/components/ui/alert';
import { Button } from '@/components/ui/button';
import { QuizQuestion } from '@/types/quiz';
import { CourseWizardData } from '@/types/course';
import { wizardSubtitleClass, wizardTitleClass } from './wizardFormClasses';
import { logger } from '@/lib/logger';

interface Step8QuizReviewProps {
  data: CourseWizardData;
  quiz?: QuizQuestion[];
  courseId?: string;
  rawContext?: string;
  onQuizUpdate: (quiz: QuizQuestion[]) => void;
}

/**
 * A module's share of the quiz. `questionIndexes` point back into the flat
 * `quiz` array so editing and insertion keep working on the single list the
 * wizard persists. `tag` is the module identity copied onto questions added
 * here, so a manual question groups with the module it was written for.
 */
interface QuizSection {
  key: string;
  title: string;
  moduleIndex?: number;
  tag?: Pick<QuizQuestion, 'moduleIndex' | 'moduleTitle'>;
  questionIndexes: number[];
}

const UNTAGGED_SECTION_KEY = 'untagged';

const formInputClass =
  'w-full rounded-[12px] border-[1.5px] border-[#e5e7ea] px-4 py-3 text-base text-[#0a0a0a] outline-none transition-colors placeholder:text-[#979797] focus:border-primary';
const formLabelClass = 'mb-2 block text-sm font-semibold text-[#666d80]';

const emptyQuestion = (): QuizQuestion => ({
  question: '',
  options: ['', '', '', ''],
  answer: 0,
  type: 'multiple_choice',
});

/**
 * Groups the flat quiz by the module each question was generated from (Phase 6
 * tags every question with `moduleIndex`/`moduleTitle`). Courses generated by
 * the single-document pipeline carry no tags, so they collapse into one section
 * named after the course.
 */
function groupQuestionsByModule(questions: QuizQuestion[], courseTitle: string): QuizSection[] {
  const byKey = new Map<string, QuizSection>();

  questions.forEach((question, index) => {
    const key =
      question.moduleIndex !== undefined
        ? `module-${question.moduleIndex}`
        : question.moduleTitle?.trim() || UNTAGGED_SECTION_KEY;

    const existing = byKey.get(key);
    if (existing) {
      existing.questionIndexes.push(index);
      return;
    }

    const isTagged = question.moduleIndex !== undefined || Boolean(question.moduleTitle?.trim());
    byKey.set(key, {
      key,
      title: question.moduleTitle?.trim() || '',
      moduleIndex: question.moduleIndex,
      tag: isTagged
        ? { moduleIndex: question.moduleIndex, moduleTitle: question.moduleTitle }
        : undefined,
      questionIndexes: [index],
    });
  });

  const sections = [...byKey.values()];
  if (sections.length === 0) {
    sections.push({ key: UNTAGGED_SECTION_KEY, title: '', questionIndexes: [] });
  }

  const onlyUntaggedSection = sections.length === 1 && !sections[0].tag;
  return sections.map((section, position) => ({
    ...section,
    title:
      section.title ||
      (onlyUntaggedSection ? courseTitle.trim() || 'Section 1' : `Section ${position + 1}`),
  }));
}

export default function Step8QuizReview({
  data,
  quiz,
  courseId,
  rawContext,
  onQuizUpdate,
}: Step8QuizReviewProps) {
  const questions = useMemo(() => quiz || [], [quiz]);
  const [addingSectionKey, setAddingSectionKey] = useState<string | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [editingIndex, setEditingIndex] = useState<number | null>(null);
  const [editingQuestion, setEditingQuestion] = useState<QuizQuestion | null>(null);
  const [newQuestion, setNewQuestion] = useState<QuizQuestion>(emptyQuestion);

  const sections = useMemo(
    () => groupQuestionsByModule(questions, data.title || ''),
    [questions, data.title],
  );

  const startAdding = (sectionKey: string) => {
    setAddingSectionKey(sectionKey);
    setNewQuestion(emptyQuestion());
  };

  const handleAddQuestion = (section: QuizSection) => {
    if (!newQuestion.question.trim() || newQuestion.options.some((o) => !o.trim())) {
      alert('Please fill in all fields.');
      return;
    }
    // Insert right after the section's last question so the flat quiz the wizard
    // persists stays grouped in module order.
    const insertAt = section.questionIndexes.length
      ? section.questionIndexes[section.questionIndexes.length - 1] + 1
      : questions.length;
    const updatedQuiz = [...questions];
    updatedQuiz.splice(insertAt, 0, { ...newQuestion, ...section.tag });

    onQuizUpdate(updatedQuiz);
    setAddingSectionKey(null);
    setNewQuestion(emptyQuestion());
  };

  const updateOption = (index: number, value: string) => {
    const newOptions = [...newQuestion.options];
    newOptions[index] = value;
    setNewQuestion({ ...newQuestion, options: newOptions });
  };

  const handleGenerateQuestion = async (section: QuizSection) => {
    const targetCourseId = courseId;
    // Fall back to title + description if rawContext isn't fully available yet
    const baseContext =
      rawContext?.trim() || `${data?.title || ''}\n${data?.description || ''}`.trim() || '';

    // The wizard only carries the merged article markdown, not each module's own
    // source text, so the module is named in the prompt rather than isolated.
    const wizardModule =
      section.moduleIndex !== undefined ? data.modules?.[section.moduleIndex] : undefined;
    const context = wizardModule
      ? [
          `Module: ${wizardModule.title}`,
          wizardModule.objective ? `Objective: ${wizardModule.objective}` : '',
          baseContext,
        ]
          .filter(Boolean)
          .join('\n\n')
      : baseContext;

    if (!targetCourseId && !context) {
      alert('Cannot generate a question right now. The course may not be fully saved yet.');
      return;
    }

    try {
      setIsGenerating(true);
      const res = await generateSingleQuestion({ courseId: targetCourseId, context });
      if (res.success && res.question) {
        setNewQuestion({
          question: res.question.question,
          options: res.question.options,
          answer: res.question.answer,
          type: res.question.type,
        });
      } else {
        alert(res.error || 'Failed to generate question with AI.');
      }
    } catch (error) {
      logger.error({ msg: 'Failed to call AI generation:', err: error });
      alert('An unexpected error occurred.');
    } finally {
      setIsGenerating(false);
    }
  };

  // Requested vs. generated: the wizard blocks publishing until at least one
  // question exists (CourseWizard.isNextDisabled). Explain that block inline, and
  // surface a partial fill (fewer than requested) as a non-blocking warning that
  // mirrors the server-side assessCourseQuality copy.
  const requestedCount = parseInt(data.quizQuestionCount ?? '', 10) || 0;
  const showEmptyBanner = questions.length === 0;
  const showPartialBanner =
    questions.length > 0 && requestedCount > 0 && questions.length < requestedCount;

  const renderAddForm = (section: QuizSection) => (
    <div className="w-full rounded-[12px] border border-[#e5e7ea] p-5">
      <h3 className="mb-5 text-lg font-bold text-foreground">Add New Question</h3>

      <div className="mb-5">
        <label className={formLabelClass} htmlFor={`newQuestionText-${section.key}`}>
          Question Text
        </label>
        <input
          id={`newQuestionText-${section.key}`}
          type="text"
          className={formInputClass}
          placeholder="Enter your question here..."
          value={newQuestion.question}
          onChange={(e) => setNewQuestion({ ...newQuestion, question: e.target.value })}
        />
      </div>

      <div className="mb-5">
        <label className={formLabelClass}>Options (Select correct answer)</label>
        <div className="flex flex-col gap-3">
          {newQuestion.options.map((opt, i) => (
            <div key={i} className="flex items-center gap-3">
              <input
                type="radio"
                name={`correctAnswer-${section.key}`}
                aria-label={`Mark option ${i + 1} correct`}
                checked={newQuestion.answer === i}
                onChange={() => setNewQuestion({ ...newQuestion, answer: i })}
              />
              <input
                type="text"
                className={formInputClass}
                value={opt}
                onChange={(e) => updateOption(i, e.target.value)}
                placeholder={`Option ${i + 1}`}
                disabled={newQuestion.type === 'true_false'}
              />
            </div>
          ))}
        </div>
      </div>

      <div className="mt-6 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <Button
          variant="outline"
          onClick={(e) => {
            e.preventDefault();
            handleGenerateQuestion(section);
          }}
          disabled={isGenerating}
        >
          {isGenerating ? (
            'Generating...'
          ) : (
            <>
              <Sparkles className="mr-2 size-3.5" />
              Generate with AI
            </>
          )}
        </Button>
        <div className="flex gap-3">
          <Button variant="ghost" onClick={() => setAddingSectionKey(null)}>
            Cancel
          </Button>
          <Button variant="default" onClick={() => handleAddQuestion(section)}>
            Save Question
          </Button>
        </div>
      </div>
    </div>
  );

  const renderQuestion = (question: QuizQuestion, index: number, positionInSection: number) => {
    if (editingIndex === index && editingQuestion) {
      return (
        <div key={index} className="w-full rounded-[12px] border border-[#e5e7ea] p-5">
          <h4 className="m-0 mb-4 text-base font-semibold">Edit Question {positionInSection}</h4>

          <div className="mb-5">
            <label className={formLabelClass} htmlFor={`editQuestionText-${index}`}>
              Question Text
            </label>
            <input
              id={`editQuestionText-${index}`}
              type="text"
              className={formInputClass}
              value={editingQuestion.question}
              onChange={(e) => setEditingQuestion({ ...editingQuestion, question: e.target.value })}
            />
          </div>

          <div className="mb-5">
            <label className={formLabelClass}>Options (Select correct answer)</label>
            <div className="flex flex-col gap-3">
              {editingQuestion.options.map((opt, i) => (
                <div key={i} className="flex items-center gap-3">
                  <input
                    type="radio"
                    name={`editCorrectAnswer-${index}`}
                    aria-label={`Mark option ${i + 1} correct`}
                    checked={editingQuestion.answer === i}
                    onChange={() => setEditingQuestion({ ...editingQuestion, answer: i })}
                  />
                  <input
                    type="text"
                    className={formInputClass}
                    value={opt}
                    onChange={(e) => {
                      const newOptions = [...editingQuestion.options];
                      newOptions[i] = e.target.value;
                      setEditingQuestion({ ...editingQuestion, options: newOptions });
                    }}
                    disabled={editingQuestion.type === 'true_false'}
                  />
                </div>
              ))}
            </div>
          </div>

          <div className="mt-6 flex justify-end gap-3">
            <Button
              variant="ghost"
              size="sm"
              onClick={() => {
                setEditingIndex(null);
                setEditingQuestion(null);
              }}
            >
              Cancel
            </Button>
            <Button
              variant="default"
              size="sm"
              onClick={() => {
                if (
                  !editingQuestion.question.trim() ||
                  editingQuestion.options.some((o) => !o.trim())
                ) {
                  alert('Please fill in all fields.');
                  return;
                }
                const updatedQuiz = [...questions];
                updatedQuiz[index] = editingQuestion;
                onQuizUpdate(updatedQuiz);
                setEditingIndex(null);
                setEditingQuestion(null);
              }}
            >
              Save Changes
            </Button>
          </div>
        </div>
      );
    }

    return (
      <div key={index} className="w-full rounded-[12px] bg-[#f8f9fb] p-5">
        <div className="mb-4 flex items-start justify-between gap-4">
          <div className="flex-1 text-base font-semibold leading-relaxed text-foreground">
            <span className="mr-2 font-bold">{positionInSection}.</span>
            {question.question}
          </div>
          <Button
            variant="outline"
            size="sm"
            className="shrink-0 rounded-[8px] border-[#e5e7ea] bg-white"
            onClick={() => {
              setEditingIndex(index);
              setEditingQuestion(question);
            }}
          >
            Edit
          </Button>
        </div>
        <div className="flex flex-col gap-2.5 pl-6">
          {question.options.map((opt, optIndex) => (
            <div
              key={optIndex}
              className="flex items-center rounded-lg border border-transparent px-3 py-2 text-sm text-text-secondary transition-colors hover:bg-background-secondary"
            >
              <div
                className={`mr-3 h-[18px] w-[18px] shrink-0 rounded-full border-2 ${
                  question.answer === optIndex
                    ? 'border-success bg-success shadow-[inset_0_0_0_3px_white]'
                    : 'border-[#cbd5e0]'
                }`}
              />
              {opt}
              {question.answer === optIndex && (
                <span className="ml-2 text-xs font-semibold text-success">(Correct)</span>
              )}
            </div>
          ))}
        </div>

        {question.explanation && (
          <div className="mt-3 rounded-lg border border-[#E2E8F0] bg-[#F7FAFC] px-4 py-3 text-[13px] leading-relaxed">
            <div className="mb-1.5 flex items-start gap-1.5 font-semibold text-[#38A169]">
              <span>✓</span>
              <span>Correct: {question.explanation.correctExplanation}</span>
            </div>
            {question.explanation.incorrectOptions &&
              Object.entries(question.explanation.incorrectOptions).map(([key, text]) => (
                <div key={key} className="mt-2 flex items-start gap-1.5 text-red-600">
                  <span>✕</span>
                  <span>
                    Option {String.fromCharCode(65 + parseInt(key))}: {text}
                  </span>
                </div>
              ))}
            {question.evidence?.moduleSectionHeading && (
              <div className="mt-2 text-[11px] text-slate-400">
                Source: {question.evidence.moduleSectionHeading}
              </div>
            )}
          </div>
        )}
      </div>
    );
  };

  return (
    <div className="flex w-full flex-col gap-10 md:gap-14">
      <div className="flex flex-col items-center gap-3">
        <h2 className={wizardTitleClass}>Review Quiz Questions</h2>
        <p className={wizardSubtitleClass}>
          Review the quiz questions generated by AI or add your own.
        </p>
      </div>

      <div className="flex w-full flex-col rounded-[12px] border-[1.5px] border-[#e5e7ea] bg-white p-5 md:p-6">
        {showEmptyBanner && (
          <Alert variant="error" title="No quiz questions were generated" className="mb-6 shrink-0">
            AI didn&apos;t generate the requested number of quiz questions. Add questions manually
            below or go back a step to retry generation.
          </Alert>
        )}
        {showPartialBanner && (
          <Alert variant="warning" title="Fewer questions than requested" className="mb-6 shrink-0">
            The quiz has only {questions.length} of the {requestedCount} requested questions. You
            can add more manually below, or go back a step to retry generation.
          </Alert>
        )}
        <div className="mb-6 flex shrink-0 items-center justify-between gap-4">
          <div className="flex flex-col">
            <div className="mb-1 text-lg font-bold text-foreground md:text-[20px]">
              Editable quiz questions
            </div>
            <div className="text-sm text-[#666d80]">{questions.length} Questions Generated</div>
          </div>
        </div>

        <Accordion
          type="multiple"
          defaultValue={sections.map((section) => section.key)}
          className="flex flex-col gap-4"
        >
          {sections.map((section) => (
            <AccordionItem
              key={section.key}
              value={section.key}
              className="border-[1.5px] border-[#e5e7ea] px-0"
            >
              <AccordionTrigger className="px-5 py-4 text-base">
                <span className="flex flex-1 items-center justify-between gap-3 pr-3">
                  <span className="font-semibold text-foreground">{section.title}</span>
                  <span className="text-sm font-normal text-[#666d80]">
                    {section.questionIndexes.length}{' '}
                    {section.questionIndexes.length === 1 ? 'question' : 'questions'}
                  </span>
                </span>
              </AccordionTrigger>
              <AccordionContent className="flex flex-col gap-5 px-5 pb-5">
                {section.questionIndexes.length === 0 ? (
                  <div className="rounded-xl border border-dashed border-border bg-background-secondary p-10 text-center italic text-text-tertiary">
                    No questions available. Add one below.
                  </div>
                ) : (
                  section.questionIndexes.map((questionIndex, positionInSection) =>
                    renderQuestion(questions[questionIndex], questionIndex, positionInSection + 1),
                  )
                )}

                {addingSectionKey === section.key ? (
                  renderAddForm(section)
                ) : (
                  <div className="flex items-center justify-between gap-4 rounded-[12px] border border-[#e5e7ea] px-5 py-4">
                    <span className="text-base font-semibold text-foreground">{section.title}</span>
                    <Button
                      variant="ghost"
                      size="icon-sm"
                      aria-label={`Add question to ${section.title}`}
                      className="shrink-0 rounded-full text-primary hover:bg-primary/10"
                      onClick={() => startAdding(section.key)}
                    >
                      <Plus className="size-5" aria-hidden="true" />
                    </Button>
                  </div>
                )}
              </AccordionContent>
            </AccordionItem>
          ))}
        </Accordion>
      </div>
    </div>
  );
}
